version: 0.0
os: linux

files:
  - source: target/ROOT.war
    destination: /opt/tomcat/webapps/ROOT.war

file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 300
      runas: root
